name: DenseNet Image Cls V2
id: 9809ad12-91cb-4519-86c5-34a6800f5f22
category: Machine Learning\Train
description: Creates a pretrained DenseNet for image classification and finetunes it, then save using sdk to model folder
inputs:
- name: Model path
  type: ModelFolder
  port: True
  description: model_path
- name: Data path
  type: GenericFolder
  port: True
  description: data_path
- name: Model type
  type: Mode
  default: 'densenet201'
  description: model_type
  options:
    - 'densenet201'
    - 'densenet169'
    - 'densenet161'
    - 'densenet121'
- name: Pretrained
  type: Boolean
  default: True
  description: pretrained
- name: Memory efficient
  type: Boolean
  default: False
  description: memory_efficient
- name: Num of classes
  type: Int
  default: 257
  description: num of classes
- name: Epochs
  type: Int
  default: 40
  description: epochs
- name: Batch size
  type: Int
  default: 128
  description: batch_size
- name: Learning rate
  type: Float
  default: 0.001
  description: learning_rate
- name: Random seed
  type: Int
  default: 1
  description: random_seed
- name: Patience
  type: Int
  default: 3
  description: patience
outputs:
- name: Label Map Path
  type: GenericFolder
  description: Contains a "index_to_label.json"
- name: Save path
  type: ModelFolder
  description: save_path
implementation:
  container:
    runConfig:
      baseDockerImage: mcr.microsoft.com/azureml/base-gpu:intelmpi2018.3-cuda10.0-cudnn7-ubuntu16.04
      gpuSupport: True
    conda:
      name: project_environment
      channels:
      - defaults
      dependencies:
      - python=3.6.2
      - pip:
        - fire==0.1.3
        - scipy==1.2.1
        - https://download.pytorch.org/whl/cu100/torch-1.1.0-cp36-cp36m-linux_x86_64.whl
        - https://download.pytorch.org/whl/cu100/torchvision-0.3.0-cp36-cp36m-linux_x86_64.whl
        - git+https://github.com/StudioCommunity/CustomModules-1.git@master#subdirectory=azureml-custom-module-examples/densenet-img-cls-v2
        - git+https://github.com/StudioCommunity/CustomModules.git@master#subdirectory=builtin-model
    command:
    - python
    - -m
    - densenetimgcls_v2.train
    args:
    - --model_path
    - inputValue: Model path
    - --data_path
    - inputValue: Data path
    - --model_type
    - inputValue: Model type
    - --pretrained
    - inputValue: Pretrained
    - --memory_efficient
    - inputValue: Memory efficient
    - --num_classes
    - inputValue: Num of classes
    - --epochs
    - inputValue: Epochs
    - --batch_size
    - inputValue: Batch size
    - --learning_rate
    - inputValue: Learning rate
    - --random_seed
    - inputValue: Random seed
    - --patience
    - inputValue: Patience
    - --label_map_path
    - outputPath: Label Map Path
    - --save_path
    - outputPath: Save path
